### ISSUE TITLE
Rename `new_hyperSpec()` → `hyperSpec()`

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hyperSpec#129]
To me, working with `new_hyperSpec()` feels a bit unnatural, so it'd be better to have a constructor function named `hyperSpec()`.

**Comment by bryanhanson** [comment]
If you do that, and you have a hyperSpec-package.R file, then ?hyperSpec would lead to two help files. R will give the user the options, of course. Just introduces an extra step, but maybe that’s fine. Certainly up to you.Sent from an undisclosed location - check with the NSA.On May 2, 2024, at 9:18 AM, Vilmantas Gegzna ***@***.***> wrote:﻿
To me, working with new_hyperSpec() feels a bit unnatural, so it'd be better to have a constructor function named hyperSpec().

**Comment by GegznaV** [comment]
Good catch. I had to create aliases as the same name cannot refer to 2 different Rd files. Now `?hyperSpec` will refer to the function and `package?hyperSpec` to the package. I'll update the NEWS file too.

![image](https://github.com/r-hyperspec/hyperSpec/assets/12725868/e795bc08-c9a6-416d-807c-01a9b5a33348)
