### ISSUE TITLE
Warnings while building vignettes

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hyperSpec#2]
While building vignettes, I get these warnings:

![image](https://user-images.githubusercontent.com/12725868/125815935-5ae8d91f-8963-417b-bd67-ba760b5c3141.png)
Text to copy:
```
Updating vignettes
Rebuilding plotting.Rmd
tweaking rgl
[WARNING] Citeproc: citation R-deldir not found
[WARNING] Citeproc: citation R-lattice not found
[WARNING] Citeproc: citation R-latticeExtra not found
[WARNING] Citeproc: citation R-plotrix not found
[WARNING] Citeproc: citation R-rgl not found
[WARNING] Citeproc: citation R-tripack not found
```

I think it is related to cbeleites/hyperSpec#275, r-hyperspec/r-hyperspec.github.io#19, and related commits.

@bryanhanson, could you take care of this?

**Comment by bryanhanson** [comment]
Yes, I will look into it w/i the hour.

**Comment by bryanhanson** [comment]
Side note: "tweaking rgl"? What does that mean?

**Comment by GegznaV** [comment]
> Side note: "tweaking rgl"? What does that mean?

I do not know, but maybe "updating default plot created with `rgl`". I think, @cbeleites can answer to this, if she wrote that code.

**Comment by bryanhanson** [comment]
Must be something CRAN added to the build and check process for some reason.
