### ISSUE TITLE
Rename `hy.getOption()`  → `hy_get_option()`, etc.

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hyperSpec#21]
For consistency with the Tidyverse style, I suggest renaming these functions:

- [x] `hy.getOption()` → `hy_get_option()`
- [x] `hy.getOptions()` → `hy_get_options()`
- [x] `hy.setOptions()`  → `hy_set_options()`

Is it OK for you, @cbeleites, @bryanhanson?

**Comment by bryanhanson** [comment]
OK by me.
