### ISSUE TITLE
Use `inherits()` instead of `is()` in `chk.hy()`

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hyperSpec#32]
I'm planning to update `chk.hy()` and related functions. This would be one of the steps.
***

The documentation of `methods::is()` says:

> Although `inherits` is defined for S3 classes, it has been modified so that the result returned is nearly always equivalent to is, both for S4 and non-S4 objects. Since it is implemented in C, it is somewhat faster. The only non-equivalences arise from use of `setIs`, which should rarely be encountered.

Is it OK for you @cbeleites, @bryanhanson  to use `inherits()` instead of `is()` in `chk.hy()`?

**Comment by bryanhanson** [comment]
I think I follow the reasoning in these related issues, they sound fine to me but CB should have the final say.
