### ISSUE TITLE
Rename `spc.label.wlonly()` → `format_label_wl_only()`, etc.

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hyperSpec#39]
The following do the formatting, so:

Current name     |     |Rename to                            | Comment
------------------| ---|-------------------------------| ---
spc.label.wlonly  | → | format_label_wl_only           | Adds label with wavelength only
spc.label.default | → | format_label_ispc_wl            | Adds label with index of i-th spectrum (`ispc`) and wavelength (default)

If you think, that `format_` is too long, we may use `fmt_`. But the first version is more explicit.

**Comment by bryanhanson** [comment]
Just curious, are these user-facing functions? There are a lot of nooks and crannies in `hyperSpec` where I've never been so I don't know off the top of my head!

**Comment by GegznaV** [comment]
They are exported.
