### ISSUE TITLE
Create function `wl_create_label_from_units()`

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hyperSpec#60]
Basing on the lines from `R/wl_convert_units.R` (see [this comment](https://github.com/r-hyperspec/hyperSpec/pull/30/files?file-filters%5B%5D=.R#r687606832) ):

```r
  x@label$.wavelength <-
    switch(.wl_fix_unit_name(to),
       nm    = expression("Wavelength, nm"),
      invcm = expression(tilde(nu) / cm^-1),
      ev    = expression("Energy / eV"),
      freq  = expression(nu / THz),
      raman = expression(Raman ~ shift / cm^-1),
      to
    )
```
A separate function should be created. The function's signature could be ~~`wl_create_label_by_units(wl_units)`~~  `wl_create_label_from_units(wl_units)` and it should return an expression with label for `@label$.wavelength`.

If this is implemented, labels in
- https://github.com/r-hyperspec/hyperSpec/issues/52
 are not necessary and the related `.R` file can be deleted.

***

Tasks:

- ~~Add unit tests for `wl_convert_units.hyperSpec()` to test if labels are correct in all cases of `to` values.~~ Moved to #69
- Create a new function #61
    - [x] Create a new function
    - [x] Create unit tests for the new function
    - [x] Update `NEWS.md`
- [x] Delete `constants-units.R` and close #52

**Comment by cbeleites** [comment]
is *by* the correct preposition? @bryanhanson ?

**Comment by bryanhanson** [comment]
"by" is OK, but "from" is better.
