### ISSUE TITLE
Why "energy" → `invcm`?

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hyperSpec#62]
In line 123 of code:

https://github.com/r-hyperspec/hyperSpec/blob/a14c9c8830766c77074aad82e16e8351d4e21a93/R/wl_convert_units.R#L123-L125

Why is "energy" converted to `invcm` (i.e., 1/cm) and not to `ev` (electronvolts)?

@ximeg, @cbeleites, @bryanhanson, what do you think?

**Comment by cbeleites** [comment]
I'd say bug.
But I'd also say that "energy" is too vague to be of any use - how should a user guess that "energy" is synonymous with electron Volts (when the spectral axis is almost always energy-related)?

BTW: I'd also suggest to **not** convert "cm" into inverse cm (!)

**Comment by GegznaV** [comment]
OK, I'd remove "energy" and "cm" from the list of options that are converted to inverted centimeters. 

If there are some the reasons why these options should be kept (Does @ximeg know any of them?), I may return them in the future.

**Comment by GegznaV** [comment]
* the reasons might be that some file formats have these options and the change might break some IO functionality.
