### ISSUE TITLE
rmmvnorm()

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hyperSpec#8]
This is old issue https://github.com/cbeleites/hyperSpec/issues/337
Unfortunately, we cannot transfer issues to other owners/organizations. 
When the old issue is solved, both the old and new issue should be closed.

**Comment by GegznaV** [comment]
What the solution to this issue should be, @cbeleites? To rename the file?

**Comment by cbeleites** [comment]
Yes, and add documentation according to what we said in the old issue discussion.

(github tells me I can transfer issues to other repos, but not from the repo owned by me to the r-hyperspec organization repo)

**Comment by GegznaV** [comment]
I've renamed the file. @sangttruong, could you take care of the rest?
