### ISSUE TITLE
deprecation process

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hyperSpec#9]
remove unit tests for deprecated file import functions, they are anyways skipped with `skip_if_not_fileio_available()`

- [x] DEPRECATED-read.asc.Andor.R
- [x] DEPRECATED-read.asc.PerkinElmer.R
- [x] DEPRECATED-read.ENVI.HySpex.R
- [x] DEPRECATED-read.ENVI.Nicolet.R
- [x] DEPRECATED-read.ENVI.R
- [x] DEPRECATED-read.ini.R
- [x] DEPRECATED-read.jdx.R
- [x] DEPRECATED-read.mat.Cytospec.R
- [x] DEPRECATED-read.mat.Witec.R
- [x] DEPRECATED-read.spc.Kaiser.R
- [x] DEPRECATED-read.spc.R
- [x] DEPRECATED-read.spe.R
- [x] DEPRECATED-read.txt.Horiba.R
- [x] DEPRECATED-read.txt.long.R
- [x] DEPRECATED-read.txt.Renishaw.R
- [x] DEPRECATED-read.txt.Shimadzu.R
- [x] DEPRECATED-read.txt.wide.R
- [x] DEPRECATED-read.txt.Witec.R
- [x] DEPRECATED-scan.R
- [x] remove `skip_if_not_fileio_available()`. This doesn't need to be deprecated. While it is exported (why?), it is a function that exclusively relates to the old directory structure of the hyperspec project.

This will remove lots of messages about skipped unit tests.

The unit tests themselves can still be looked up easily in the old hyperSpec repo at https://github.com/cbeleites/hyperSpec/

**Comment by GegznaV** [comment]
> While it is exported (why?), it is a function that exclusively relates to the old directory structure of the hyperspec project.

Unit tests in other packages use this function. These unit tests must be updated/fixed.

**Comment by cbeleites** [comment]
Yes. Having this function in the other packages means that the unit tests were always skipped, so that needs to be fixed in the new packages.

**Comment by GegznaV** [comment]
The only package that uses `skip_if_not_fileio_available()` is `hySpc.read.ENVI`
